packages:
  - addok
  - addok-france
  - addok-fr
  - addok-sqlite-store
  - addok-csv
settings: remote/france/addok.conf
data_uri: http://bano.openstreetmap.fr/BAN_odbl/BAN_odbl.json.bz2
domain: addok.space
processes: 8
